CREATE TABLE files (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fkObjectId int(11) NOT NULL,
    name VARCHAR(60) NOT NULL,
    file LONGBLOB NOT NULL,
    file_type VARCHAR(60) NOT NULL,
    file_size INT(20) NOT NULL,
	crc varchar(128) NOT NULL,
	created datetime DEFAULT NULL
);

DROP TRIGGER IF EXISTS `FILES_CREATE_TIMESTAMP`;
DELIMITER //
CREATE TRIGGER `FILES_CREATE_TIMESTAMP` BEFORE INSERT ON `files`
 FOR EACH ROW SET NEW.CREATED = NOW()
//
DELIMITER ;