CREATE TABLE files (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    file BLOB NOT NULL,
    file_type VARCHAR(60) NOT NULL,
    file_size INT UNSIGNED NOT NULL
)